on: [push]

name: Test JS bindings

jobs:
  test-js:
    runs-on: ubuntu-latest
    container: ghcr.io/artifactdb/chihaya.js-docker/builder:master
    defaults:
      run:
        working-directory: /chihaya.js

    steps:
    - name: Get to the right branch
      run: |
        git fetch --all
        git checkout $GITHUB_SHA

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Update node build 
      run: |
        cd wasm
        bash build.sh

    - name: Update NPM packages
      run: npm i --include=dev

    - name: Run tests
      run: npm run test
